"""User configuration models and P0 configuration processing.

This module implements the P0 layer - user preference collection and processing
that runs before ingestion and shapes the entire downstream pipeline.
"""

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class TonePreferences(BaseModel):
    """User's desired output tone and register."""

    overall: str = ""
    vs_original: str = Field(
        default="faithful",
        pattern="^(faithful|darker|lighter|more_psychological|divergent)$",
    )
    specific_notes: str = ""


class EmphasisPreferences(BaseModel):
    """What aspects of the story the user wants emphasized."""

    primary: List[str] = Field(default_factory=list)
    deprioritize: List[str] = Field(default_factory=list)
    notes: str = ""


class DivergenceSeed(BaseModel):
    """A user-specified desired divergence from the original story.

    Seeds work as soft pressure, not hard overrides:
    - Strong seeds: injected as high-priority goal stack entries
    - Gentle seeds: increase salience weights for opportunities
    """

    description: str
    character_id: Optional[str] = None
    tick_hint: Optional[str] = None
    strength: str = Field(default="gentle", pattern="^(strong|gentle)$")


class ChapterFormat(BaseModel):
    """User preferences for output chapter structure."""

    target_word_count: int = Field(default=2000, ge=500, le=10000)
    pov_style: str = Field(
        default="alternating",
        pattern="^(alternating|single|close_third|omniscient)$",
    )
    story_time_per_chapter: str = ""
    chapter_structure: str = Field(
        default="match_original",
        pattern="^(match_original|user_defined)$",
    )


class UserMeta(BaseModel):
    """Complete user configuration object.

    This is generated by P0 (configuration processing) and injected into
    the [META] section of all downstream prompts. It shapes:
    - Ingestion emphasis during P1.x extraction
    - Salience scoring during simulation
    - Narrative synthesis during P5.x output
    """

    tone: TonePreferences = Field(default_factory=TonePreferences)
    emphasis: EmphasisPreferences = Field(default_factory=EmphasisPreferences)
    divergence_seeds: List[DivergenceSeed] = Field(default_factory=list)
    focus_characters: List[str] = Field(default_factory=list)
    chapter_format: ChapterFormat = Field(default_factory=ChapterFormat)
    free_notes: str = ""
